version: "3.8"
services:
  backend:
    image: marzia256/my-backend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    command: npm start

  frontend:
    image: marzia256/my-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start
