name: Docker Pull and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull frontend Docker image
        run: |
          docker pull marzia256/my-frontend:latest

      - name: Pull backend Docker image
        run: |
          docker pull marzia256/my-backend:latest

      - name: Run frontend container
        run: |
          docker run -d -p 3000:3000 marzia256/my-frontend:latest

      - name: Run backend container
        run: |
          docker run -d -p 3001:3001 marzia256/my-backend:latest
      - name: Stop and remove containers
        run: |
          docker stop $(docker ps -q) && docker rm $(docker ps -a -q)
